// @ts-check

/** @typedef {import("../diagnostics/index.js").DiagnosticCollector} DiagnosticCollector */
/** @typedef {import("../diagnostics/index.js").Diagnostic} Diagnostic */
/** @typedef {import("../diagnostics/index.js").DiagnosticCode} DiagnosticCode */
/** @typedef {import("./types.js").ProjectNode} ProjectNode */
/** @typedef {import("./types.js").FeatureNode} FeatureNode */
/** @typedef {import("./types.js").RouteNode} RouteNode */
/** @typedef {import("./types.js").PageNode} PageNode */
/** @typedef {import("./types.js").AssetNode} AssetNode */
/** @typedef {import("./types.js").IslandNode} IslandNode */
/** @typedef {import("./types.js").ImageNode} ImageNode */
/** @typedef {import("./types.js").BuildArtifact} BuildArtifact */
/** @typedef {import("./types.js").ProjectGraphSnapshot} ProjectGraphSnapshot */

export class ProjectGraph {
  #project
  #diagnostics
  #features = new Map()
  #routes = new Map()
  #pages = new Map()
  #assets = new Map()
  #islands = new Map()
  #images = new Map()
  #artifacts = new Map()
  /**
   * @param {ProjectGraphSnapshot} snapshot
   * @param {DiagnosticCollector} diagnostics
   */
  static fromSnapshot(snapshot, diagnostics) {
    const graph = new ProjectGraph(snapshot.project, diagnostics)
    for (const node of snapshot.features.values()) graph.addFeature(node)
    for (const node of snapshot.routes.values()) graph.addRoute(node)
    for (const node of snapshot.pages.values()) graph.addPage(node)
    for (const node of snapshot.assets.values()) graph.addAsset(node)
    for (const node of snapshot.islands.values()) graph.addIsland(node)
    for (const node of snapshot.images.values()) graph.addImage(node)
    for (const node of snapshot.artifacts.values()) graph.addArtifact(node)
    return graph
  }
  /**
   * @param {ProjectNode} project
   * @param {DiagnosticCollector} diagnostics
   */
  constructor(project, diagnostics) {
    this.#project = Object.freeze({ ...project })
    this.#diagnostics = diagnostics
  }
  /** @param {FeatureNode} node */
  addFeature(node) {
    return this.#insert(this.#features, node, "MINISTA_FEATURE_DUPLICATE")
  }
  /** @param {RouteNode} node */
  addRoute(node) {
    const duplicatePattern = [...this.#routes.values()].find((route) => route.pattern === node.pattern && route.id !== node.id)
    if (duplicatePattern) {
      return this.#diagnostics.error({
        code: "MINISTA_ROUTE_DUPLICATE",
        message: `Route pattern ${node.pattern} is already provided by ${duplicatePattern.sourceFile}.`,
        nodeId: node.id,
        location: { file: node.sourceFile },
        related: [
          {
            message: "First route is defined here.",
            location: { file: duplicatePattern.sourceFile },
          },
        ],
      })
    }
    return this.#insert(this.#routes, node, "MINISTA_ROUTE_DUPLICATE")
  }
  /** @param {PageNode} node */
  addPage(node) {
    if (!this.#routes.has(node.routeId)) {
      return this.#diagnostics.error({
        code: "MINISTA_PAGE_ROUTE_NOT_FOUND",
        message: `Page ${node.id} references unknown route ${node.routeId}.`,
        nodeId: node.id,
        phase: "resolve",
      })
    }
    const duplicateUrl = [...this.#pages.values()].find((page) => page.url === node.url && page.id !== node.id)
    if (duplicateUrl) {
      return this.#diagnostics.error({
        code: "MINISTA_PAGE_URL_DUPLICATE",
        message: `Page URL ${node.url} is already generated by ${duplicateUrl.id}.`,
        nodeId: node.id,
        phase: "resolve",
      })
    }
    return this.#insert(this.#pages, node, "MINISTA_PAGE_DUPLICATE")
  }
  /** @param {AssetNode} node */
  addAsset(node) {
    const current = this.#assets.get(node.id)
    if (current) {
      this.#assets.set(node.id, Object.freeze({
        ...current,
        ...node,
        consumers: Object.freeze([
          ...new Set([...current.consumers, ...node.consumers]),
        ]),
        output: node.output ?? current.output,
      }))
      return undefined
    }
    return this.#insert(this.#assets, node, "MINISTA_ASSET_DUPLICATE")
  }
  /** @param {IslandNode} node */
  addIsland(node) {
    const current = this.#islands.get(node.id)
    if (current) {
      this.#islands.set(node.id, Object.freeze({
        ...current,
        ...node,
        pages: Object.freeze([...new Set([...current.pages, ...node.pages])]),
      }))
      return undefined
    }
    return this.#insert(this.#islands, node, "MINISTA_ISLAND_DUPLICATE")
  }
  /** @param {ImageNode} node */
  addImage(node) {
    const current = this.#images.get(node.id)
    if (current) {
      this.#images.set(node.id, Object.freeze({
        ...current,
        ...node,
        pages: Object.freeze([...new Set([...current.pages, ...node.pages])]),
        generatedAssets: Object.freeze([
          ...new Set([...current.generatedAssets, ...node.generatedAssets]),
        ]),
      }))
      return undefined
    }
    return this.#insert(this.#images, node, "MINISTA_IMAGE_DUPLICATE")
  }
  /** @param {BuildArtifact} node */
  addArtifact(node) {
    if (!this.#features.has(node.owner)) {
      return this.#diagnostics.error({
        code: "MINISTA_ARTIFACT_OWNER_NOT_FOUND",
        message: `Artifact ${node.id} references unknown feature ${node.owner}.`,
        nodeId: node.id,
      })
    }
    return this.#insert(this.#artifacts, node, "MINISTA_ARTIFACT_DUPLICATE")
  }
  /** @param {ReadonlySet<import("./ids.js").FeatureId>} owners */
  removeArtifactsByOwner(owners) {
    for (const [id, artifact] of this.#artifacts) {
      if (owners.has(artifact.owner)) this.#artifacts.delete(id)
    }
  }
  /** @param {ReadonlySet<import("./ids.js").ArtifactId>} ids */
  removeArtifacts(ids) {
    for (const id of ids) this.#artifacts.delete(id)
  }
  /** @returns {ProjectGraphSnapshot} */
  snapshot() {
    return Object.freeze({
      schemaVersion: "1",
      project: this.#project,
      features: new Map(this.#features),
      routes: new Map(this.#routes),
      pages: new Map(this.#pages),
      assets: new Map(this.#assets),
      islands: new Map(this.#islands),
      images: new Map(this.#images),
      artifacts: new Map(this.#artifacts),
    })
  }
  /**
   * @template {string} Id
   * @template {{readonly id: Id}} Node
   * @param {Map<Id, Node>} map
   * @param {Node} node
   * @param {DiagnosticCode} code
   */
  #insert(map, node, code) {
    const current = map.get(node.id)
    if (current) {
      if (JSON.stringify(current) === JSON.stringify(node)) return undefined
      return this.#diagnostics.error({
        code,
        message: `Graph node ${node.id} is already registered.`,
        nodeId: node.id,
      })
    }
    map.set(node.id, Object.freeze({ ...node }))
    return undefined
  }
}
