// @ts-check

/** @typedef {import("../diagnostics/index.js").DiagnosticCollector} DiagnosticCollector */
/** @typedef {import("../diagnostics/index.js").Diagnostic} Diagnostic */
/** @typedef {import("../diagnostics/index.js").DiagnosticCode} DiagnosticCode */
/** @typedef {import("./types.js").ProjectNode} ProjectNode */
/** @typedef {import("./types.js").FeatureNode} FeatureNode */
/** @typedef {import("./types.js").RouteNode} RouteNode */
/** @typedef {import("./types.js").PageNode} PageNode */
/** @typedef {import("./types.js").AssetNode} AssetNode */
/** @typedef {import("./types.js").IslandNode} IslandNode */
/** @typedef {import("./types.js").ImageNode} ImageNode */
/** @typedef {import("./types.js").BuildArtifact} BuildArtifact */
/** @typedef {import("./types.js").ProjectGraphSnapshot} ProjectGraphSnapshot */

export class ProjectGraph {
  #project
  #diagnostics
  /** @type {Map<FeatureNode["id"], FeatureNode>} */
  #features = new Map()
  /** @type {Map<RouteNode["id"], RouteNode>} */
  #routes = new Map()
  /** @type {Map<string, RouteNode["id"]>} */
  #routeIdsByPattern = new Map()
  /** @type {Map<PageNode["id"], PageNode>} */
  #pages = new Map()
  /** @type {Map<string, PageNode["id"]>} */
  #pageIdsByUrl = new Map()
  /** @type {Map<AssetNode["id"], AssetNode>} */
  #assets = new Map()
  /** @type {Map<IslandNode["id"], IslandNode>} */
  #islands = new Map()
  /** @type {Map<ImageNode["id"], ImageNode>} */
  #images = new Map()
  /** @type {Map<BuildArtifact["id"], BuildArtifact>} */
  #artifacts = new Map()
  /**
   * @param {ProjectGraphSnapshot} snapshot
   * @param {DiagnosticCollector} diagnostics
   */
  static fromSnapshot(snapshot, diagnostics) {
    const graph = new ProjectGraph(snapshot.project, diagnostics)
    for (const node of snapshot.features.values()) graph.addFeature(node)
    for (const node of snapshot.routes.values()) graph.addRoute(node)
    for (const node of snapshot.pages.values()) graph.addPage(node)
    for (const node of snapshot.assets.values()) graph.addAsset(node)
    for (const node of snapshot.islands.values()) graph.addIsland(node)
    for (const node of snapshot.images.values()) graph.addImage(node)
    for (const node of snapshot.artifacts.values()) graph.addArtifact(node)
    return graph
  }
  /**
   * @param {ProjectNode} project
   * @param {DiagnosticCollector} diagnostics
   */
  constructor(project, diagnostics) {
    this.#project = Object.freeze({ ...project })
    this.#diagnostics = diagnostics
  }
  /** @param {FeatureNode} node */
  addFeature(node) {
    return this.#insert(this.#features, node, "MINISTA_FEATURE_DUPLICATE")
  }
  /** @param {RouteNode} node */
  addRoute(node) {
    const duplicateId = this.#routeIdsByPattern.get(node.pattern)
    if (duplicateId !== undefined && duplicateId !== node.id) {
      const duplicate = this.#routes.get(duplicateId)
      const duplicateSource = duplicate?.sourceFile ?? node.sourceFile
      return this.#diagnostics.error({
        code: "MINISTA_ROUTE_DUPLICATE",
        message: `Route pattern ${node.pattern} is already provided by ${duplicateSource}.`,
        nodeId: node.id,
        location: { file: node.sourceFile },
        related: [
          {
            message: "First route is defined here.",
            location: { file: duplicateSource },
          },
        ],
      })
    }
    const diagnostic = this.#insert(this.#routes, node, "MINISTA_ROUTE_DUPLICATE")
    if (!diagnostic) this.#routeIdsByPattern.set(node.pattern, node.id)
    return diagnostic
  }
  /** @param {PageNode} node */
  addPage(node) {
    if (!this.#routes.has(node.routeId)) {
      return this.#diagnostics.error({
        code: "MINISTA_PAGE_ROUTE_NOT_FOUND",
        message: `Page ${node.id} references unknown route ${node.routeId}.`,
        nodeId: node.id,
        phase: "resolve",
      })
    }
    const duplicateId = this.#pageIdsByUrl.get(node.url)
    if (duplicateId !== undefined && duplicateId !== node.id) {
      return this.#diagnostics.error({
        code: "MINISTA_PAGE_URL_DUPLICATE",
        message: `Page URL ${node.url} is already generated by ${duplicateId}.`,
        nodeId: node.id,
        phase: "resolve",
      })
    }
    const diagnostic = this.#insert(this.#pages, node, "MINISTA_PAGE_DUPLICATE")
    if (!diagnostic) this.#pageIdsByUrl.set(node.url, node.id)
    return diagnostic
  }
  /** @param {FeatureNode["id"]} id */
  hasFeature(id) {
    return this.#features.has(id)
  }
  /** @param {RouteNode["id"]} id */
  getRoute(id) {
    return this.#routes.get(id)
  }
  /** @param {string} pattern */
  getRouteIdByPattern(pattern) {
    return this.#routeIdsByPattern.get(pattern)
  }
  /** @param {string} pattern */
  getRouteByPattern(pattern) {
    const id = this.getRouteIdByPattern(pattern)
    return id === undefined ? undefined : this.#routes.get(id)
  }
  /** @param {PageNode["id"]} id */
  getPage(id) {
    return this.#pages.get(id)
  }
  /** @param {string} url */
  getPageIdByUrl(url) {
    return this.#pageIdsByUrl.get(url)
  }
  /** @param {string} url */
  getPageByUrl(url) {
    const id = this.getPageIdByUrl(url)
    return id === undefined ? undefined : this.#pages.get(id)
  }
  /** @returns {IterableIterator<PageNode>} */
  listPages() {
    return this.#pages.values()
  }
  /** @param {RouteNode} node */
  updateRoute(node) {
    const current = this.#routes.get(node.id)
    if (!current) return this.addRoute(node)
    const duplicateId = this.#routeIdsByPattern.get(node.pattern)
    if (duplicateId !== undefined && duplicateId !== node.id) {
      return this.addRoute(node)
    }
    this.#routes.set(node.id, Object.freeze({ ...node }))
    if (current.pattern !== node.pattern) this.#routeIdsByPattern.delete(current.pattern)
    this.#routeIdsByPattern.set(node.pattern, node.id)
    return undefined
  }
  /** @param {PageNode} node */
  updatePage(node) {
    const current = this.#pages.get(node.id)
    if (!current) return this.addPage(node)
    if (!this.#routes.has(node.routeId)) return this.addPage(node)
    const duplicateId = this.#pageIdsByUrl.get(node.url)
    if (duplicateId !== undefined && duplicateId !== node.id) {
      return this.addPage(node)
    }
    this.#pages.set(node.id, Object.freeze({ ...node }))
    if (current.url !== node.url) this.#pageIdsByUrl.delete(current.url)
    this.#pageIdsByUrl.set(node.url, node.id)
    return undefined
  }
  /** @param {RouteNode["id"]} id */
  removeRoute(id) {
    const route = this.#routes.get(id)
    if (!route) return false
    this.#routes.delete(id)
    this.#routeIdsByPattern.delete(route.pattern)
    for (const page of this.#pages.values()) {
      if (page.routeId === id) this.removePage(page.id)
    }
    return true
  }
  /** @param {PageNode["id"]} id */
  removePage(id) {
    const page = this.#pages.get(id)
    if (!page) return false
    this.#pages.delete(id)
    this.#pageIdsByUrl.delete(page.url)
    for (const [assetId, asset] of this.#assets) {
      if (!asset.consumers.includes(id)) continue
      this.#assets.set(assetId, Object.freeze({
        ...asset,
        consumers: Object.freeze(asset.consumers.filter((pageId) => pageId !== id)),
      }))
    }
    for (const [islandId, island] of this.#islands) {
      if (!island.pages.includes(id)) continue
      this.#islands.set(islandId, Object.freeze({
        ...island,
        pages: Object.freeze(island.pages.filter((pageId) => pageId !== id)),
      }))
    }
    for (const [imageId, image] of this.#images) {
      if (!image.pages.includes(id)) continue
      this.#images.set(imageId, Object.freeze({
        ...image,
        pages: Object.freeze(image.pages.filter((pageId) => pageId !== id)),
      }))
    }
    const removedArtifactIds = new Set()
    for (const [artifactId, artifact] of this.#artifacts) {
      if (artifact.scope?.kind !== "page" || artifact.scope.pageId !== id) continue
      removedArtifactIds.add(artifactId)
      this.#artifacts.delete(artifactId)
    }
    if (removedArtifactIds.size > 0) {
      for (const [artifactId, artifact] of this.#artifacts) {
        if (!artifact.dependencies.some((dependency) => removedArtifactIds.has(dependency))) continue
        this.#artifacts.set(artifactId, Object.freeze({
          ...artifact,
          dependencies: Object.freeze(
            artifact.dependencies.filter((dependency) => !removedArtifactIds.has(dependency)),
          ),
        }))
      }
    }
    return true
  }
  /** @param {AssetNode} node */
  addAsset(node) {
    const current = this.#assets.get(node.id)
    if (current) {
      this.#assets.set(node.id, Object.freeze({
        ...current,
        ...node,
        consumers: Object.freeze([
          ...new Set([...current.consumers, ...node.consumers]),
        ]),
        output: node.output ?? current.output,
      }))
      return undefined
    }
    return this.#insert(this.#assets, node, "MINISTA_ASSET_DUPLICATE")
  }
  /** @param {IslandNode} node */
  addIsland(node) {
    const current = this.#islands.get(node.id)
    if (current) {
      this.#islands.set(node.id, Object.freeze({
        ...current,
        ...node,
        pages: Object.freeze([...new Set([...current.pages, ...node.pages])]),
      }))
      return undefined
    }
    return this.#insert(this.#islands, node, "MINISTA_ISLAND_DUPLICATE")
  }
  /** @param {ImageNode} node */
  addImage(node) {
    const current = this.#images.get(node.id)
    if (current) {
      this.#images.set(node.id, Object.freeze({
        ...current,
        ...node,
        pages: Object.freeze([...new Set([...current.pages, ...node.pages])]),
        generatedAssets: Object.freeze([
          ...new Set([...current.generatedAssets, ...node.generatedAssets]),
        ]),
      }))
      return undefined
    }
    return this.#insert(this.#images, node, "MINISTA_IMAGE_DUPLICATE")
  }
  /** @param {BuildArtifact} node */
  addArtifact(node) {
    if (!this.#features.has(node.owner)) {
      return this.#diagnostics.error({
        code: "MINISTA_ARTIFACT_OWNER_NOT_FOUND",
        message: `Artifact ${node.id} references unknown feature ${node.owner}.`,
        nodeId: node.id,
      })
    }
    return this.#insert(this.#artifacts, node, "MINISTA_ARTIFACT_DUPLICATE")
  }
  /** @param {ReadonlySet<import("./ids.js").FeatureId>} owners */
  removeArtifactsByOwner(owners) {
    for (const [id, artifact] of this.#artifacts) {
      if (owners.has(artifact.owner)) this.#artifacts.delete(id)
    }
  }
  /** @param {ReadonlySet<import("./ids.js").ArtifactId>} ids */
  removeArtifacts(ids) {
    for (const id of ids) this.#artifacts.delete(id)
  }
  /** @returns {ProjectGraphSnapshot} */
  snapshot() {
    return Object.freeze({
      schemaVersion: "1",
      project: this.#project,
      features: new Map(this.#features),
      routes: new Map(this.#routes),
      pages: new Map(this.#pages),
      assets: new Map(this.#assets),
      islands: new Map(this.#islands),
      images: new Map(this.#images),
      artifacts: new Map(this.#artifacts),
    })
  }
  /**
   * @template {string} Id
   * @template {{readonly id: Id}} Node
   * @param {Map<Id, Node>} map
   * @param {Node} node
   * @param {DiagnosticCode} code
   */
  #insert(map, node, code) {
    const current = map.get(node.id)
    if (current) {
      if (JSON.stringify(current) === JSON.stringify(node)) return undefined
      return this.#diagnostics.error({
        code,
        message: `Graph node ${node.id} is already registered.`,
        nodeId: node.id,
      })
    }
    map.set(node.id, Object.freeze({ ...node }))
    return undefined
  }
}
