import type { Diagnostic } from "../diagnostics/index.js"
import type { DiagnosticCollector } from "../diagnostics/index.js"
import type {
  ArtifactId,
  AssetId,
  FeatureId,
  ImageId,
  IslandId,
  PageId,
  RouteId,
} from "./ids.js"
import type {
  AssetNode,
  BuildArtifact,
  FeatureNode,
  ImageNode,
  IslandNode,
  PageNode,
  ProjectGraphSnapshot,
  ProjectNode,
  RouteNode,
} from "./types.js"

type GraphNode =
  | FeatureNode
  | RouteNode
  | PageNode
  | AssetNode
  | IslandNode
  | ImageNode
  | BuildArtifact

export class ProjectGraph {
  readonly #project: ProjectNode
  readonly #diagnostics: DiagnosticCollector
  readonly #features = new Map<FeatureId, FeatureNode>()
  readonly #routes = new Map<RouteId, RouteNode>()
  readonly #pages = new Map<PageId, PageNode>()
  readonly #assets = new Map<AssetId, AssetNode>()
  readonly #islands = new Map<IslandId, IslandNode>()
  readonly #images = new Map<ImageId, ImageNode>()
  readonly #artifacts = new Map<ArtifactId, BuildArtifact>()

  constructor(project: ProjectNode, diagnostics: DiagnosticCollector) {
    this.#project = Object.freeze({ ...project })
    this.#diagnostics = diagnostics
  }

  addFeature(node: FeatureNode): Diagnostic | undefined {
    return this.#insert(this.#features, node, "MINISTA_FEATURE_DUPLICATE")
  }

  addRoute(node: RouteNode): Diagnostic | undefined {
    const duplicatePattern = [...this.#routes.values()].find(
      (route) => route.pattern === node.pattern && route.id !== node.id,
    )
    if (duplicatePattern) {
      return this.#diagnostics.error({
        code: "MINISTA_ROUTE_DUPLICATE",
        message: `Route pattern ${node.pattern} is already provided by ${duplicatePattern.sourceFile}.`,
        nodeId: node.id,
        location: { file: node.sourceFile },
        related: [
          {
            message: "First route is defined here.",
            location: { file: duplicatePattern.sourceFile },
          },
        ],
      })
    }
    return this.#insert(this.#routes, node, "MINISTA_ROUTE_DUPLICATE")
  }

  addPage(node: PageNode): Diagnostic | undefined {
    if (!this.#routes.has(node.routeId)) {
      return this.#diagnostics.error({
        code: "MINISTA_PAGE_ROUTE_NOT_FOUND",
        message: `Page ${node.id} references unknown route ${node.routeId}.`,
        nodeId: node.id,
        phase: "resolve",
      })
    }
    const duplicateUrl = [...this.#pages.values()].find(
      (page) => page.url === node.url && page.id !== node.id,
    )
    if (duplicateUrl) {
      return this.#diagnostics.error({
        code: "MINISTA_PAGE_URL_DUPLICATE",
        message: `Page URL ${node.url} is already generated by ${duplicateUrl.id}.`,
        nodeId: node.id,
        phase: "resolve",
      })
    }
    return this.#insert(this.#pages, node, "MINISTA_PAGE_DUPLICATE")
  }

  addAsset(node: AssetNode): Diagnostic | undefined {
    return this.#insert(this.#assets, node, "MINISTA_ASSET_DUPLICATE")
  }

  addIsland(node: IslandNode): Diagnostic | undefined {
    return this.#insert(this.#islands, node, "MINISTA_ISLAND_DUPLICATE")
  }

  addImage(node: ImageNode): Diagnostic | undefined {
    return this.#insert(this.#images, node, "MINISTA_IMAGE_DUPLICATE")
  }

  addArtifact(node: BuildArtifact): Diagnostic | undefined {
    if (!this.#features.has(node.owner)) {
      return this.#diagnostics.error({
        code: "MINISTA_ARTIFACT_OWNER_NOT_FOUND",
        message: `Artifact ${node.id} references unknown feature ${node.owner}.`,
        nodeId: node.id,
      })
    }
    return this.#insert(
      this.#artifacts,
      node,
      "MINISTA_ARTIFACT_DUPLICATE",
    )
  }

  snapshot(): ProjectGraphSnapshot {
    return Object.freeze({
      schemaVersion: "1",
      project: this.#project,
      features: new Map(this.#features),
      routes: new Map(this.#routes),
      pages: new Map(this.#pages),
      assets: new Map(this.#assets),
      islands: new Map(this.#islands),
      images: new Map(this.#images),
      artifacts: new Map(this.#artifacts),
    })
  }

  #insert<Id extends string, Node extends GraphNode>(
    map: Map<Id, Node>,
    node: Node & { readonly id: Id },
    code: `MINISTA_${string}`,
  ): Diagnostic | undefined {
    if (map.has(node.id)) {
      return this.#diagnostics.error({
        code,
        message: `Graph node ${node.id} is already registered.`,
        nodeId: node.id,
      })
    }
    map.set(node.id, Object.freeze({ ...node }) as unknown as Node)
    return undefined
  }
}
